spring:
  application:
    name: shortlink-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/booking
#    username: user
#    password: password
#    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
